#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  echo 'Usage: `add-path <path>`'
  exit 1
fi

if [ ! -d "$1" ]; then
  echo "The path is not a valid directory"
  exit 1
fi

if [[ ":$PATH:" != *":$1:"* ]]; then
  PATH="${PATH:+"$PATH:"}$1"
else
  echo "The path is already in PATH"
fi
