#!/usr/bin/env bash

# Resize an image's canvas with transparence

if [ $# -lt 2 ]; then
  echo 'Usage: `imageexpand <file> <size>`'
  exit 1
fi

file="$1"
size="$2"

if [ ! -r "$file" ]; then
  echo "Image '$file' does not exist"
  exit 1
fi

convert "$file" -gravity Center -background transparent -extend "$size" "$file"
