#!/usr/bin/env bash
uname="$(uname -s)"

if [ "$uname" == "Darwin" ]; then
  echo "osx"
elif [ "$(expr substr "$uname" 1 5)" == "Linux" ]; then
  echo "linux"
elif [ "$(expr substr "$uname" 1 10)" == "MINGW32_NT" ]; then
  echo "cygwin"
else
  exit 1
fi
