#!/usr/bin/env bash

# Create a .tar.gz archive, using `zopfli`, `pigz` or `gzip` for compression

tmpFile="${@%/}.tar"
tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || exit 1

size=$(stat -c"%s" "${tmpFile}" 2> /dev/null)
cmd="gzip"

if (( size < 52428800 )) && is-command zopfli; then
  # The .tar file is smaller than 50 MB and Zopfli is available
  cmd="zopfli"
elif [ is-command pigz ]; then
  cmd="pigz"
fi

echo "Compressing .tar using \`${cmd}\`…"
"${cmd}" -v "${tmpFile}" || exit 1

[ -f "${tmpFile}" ] && rm "${tmpFile}"
echo "${tmpFile}.gz created successfully"
